
default: exetarget

LIBS =	\
		-ljogo \
		-lpontuacao \
		-lpeca \
		-lgui \
		-lutil \
		-lmckpeca \
		-lmckgui \

SUBDIRS =

OBJS =	\
		testeControladorTabuleiro.o \
		testeSituacao.o \

include $(COLUNAS_DIR)/tst/tst.mk
