
default: exetarget

EXE=colunas.exe

GRAPHLIBS =	\
			-lSDL2 \
			-lSDL2_image \
			-lSDL2_ttf \

LIBS =	\
		-lgraficoSDL \
		-lgrafico \
		-ljogo \
		-lpeca \
		-lgui \
		-lpontuacao \
		-lutil \
		$(GRAPHLIBS) \

SUBDIRS =

OBJS =	\
		colunas.o \

include $(COLUNAS_DIR)/src/src.mk
