
default: exetarget

LIBS =	\
		-lmckpeca \
		-lmckgui \
		-lpeca \
		-lgui \
		-lutil \

SUBDIRS =

OBJS =	\
		testePeca.o \
		testePosicaoPeca.o \
		testeTabuleiro.o \

include $(COLUNAS_DIR)/tst/tst.mk
