
default: subdirs

LIBDIRS =	\
			util \
			gui \
			peca \
			pontuacao \
			jogo \
			grafico \

SUBDIRS =	\
			$(LIBDIRS) \
			colunas \

colunas:	$(LIBDIRS) \

subdirs: $(SUBDIRS)

include src.mk
